version: '3'
services:
  nginx_client:
    image: nginx:latest
    container_name: YinMusicClient
    ports:
      - "8080:8080"
    volumes:
      - ./client/html:/usr/share/nginx/html
      - ./client/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
    depends_on:
      - web

  nginx_manage:
    image: nginx:latest
    container_name: YinMusicManage
    ports:
      - "8081:8080"
    volumes:
      - ./manage/html:/usr/share/nginx/html
      - ./manage/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
    depends_on:
      - web

  web:
    build: .
    container_name: YinMusicWebServer
    ports:
      - "8888:8888"
    depends_on:
      - db
      - minio
      - redis
  db:
    image: mysql:8.0
    container_name: YinMysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tp_music
# 使用minio
  minio:
      image: minio/minio
      container_name: YinMinio
      ports:
        - "9000:9000"
        - "40753:40753"
      environment:
        MINIO_ROOT_USER: root
        MINIO_ROOT_PASSWORD: 123456789
      volumes:
      - ./minio/data:/data
      command: server /data --console-address ":40753"
# 使用redis7.0

  redis:
    image: redis:7.0
    container_name: YinRedis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /etc/redis/redis.conf --appendonly yes
