# 使用官方的Python 3.8镜像作为基础镜像
FROM python:3.8-slim

# 设置工作目录
WORKDIR /app

# 安装系统依赖
RUN apt-get update && apt-get install -y \
    libmariadb-dev \
    pkg-config \
    gcc \
    libhdf5-dev \
    && rm -rf /var/lib/apt/lists/*

# 复制项目文件，需要配合docker-compose.yml使用，不可以单独使用，
# 因为在docker-compose.yml中，需要将context设置为../music-recommend-service
# 记得修改config.py中的数据库连接信息
COPY recommendation_service /app/

# 安装Python依赖
RUN pip install --no-cache-dir -r /app/requirements.txt

# 设置环境变量
ENV PYTHONPATH=/app

# 运行调度器
CMD ["python", "scheduler.py"] 